language: java

jdk:
- oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.sonar"

before_install:
- chmod -R +x .

install: "./gradle clean"

jobs:
  include:
    - stage: "Test"
      script: "./gradlew check"
    - stage: "Quality"
      script: "./gradlew sonarqube -Dsonar.host.url=http://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=hobynye -Dsonar.branch.name=$TRAVIS_BRANCH"
    - stage: "Deploy"
      script: "./gradlew assemble"
      deploy:
        provider: releases
        api_key:
          secure: edLmj1E7TIigBaJCGbuiIU1n70X5tuPlX5M3w6SxkjeIS+U5liv2duz19aVEawGj7+CfSDFmUqsH7eyW1GnO0eN4GSM+dDPsgyMDbqesK493V8vYBWKvO/uyXAJeIJaiY7FP8Ifyukcmdhwp+9BlV2JKwWoWcElYYDDi5ZF7Zw4vaIlmYKBXkPmb27FT0+n1FaYNcmtg4VtgIqVxyrDacHgZajS62Cw+MB4x3p7fDscUUtPp9e8483hNnIQSVQJj2solyvgiKmL2703moh+oo5z5pnX1+GvdGWo+prj1hTlsf6bT0YCjQEjAlFPRtFgnWvjWIjRN0oG2FHXf+56NdDaglxUsaWvPKjqGe/nEblR0B8zfvPYfs7KVN14Fv6AaY3NjUZGGqyUYROAa4Sk/h+d9nxUC10QN7TQgR6KunOSF0xZarNoWG5BvDf/PFJIxIUu3qfCDya3LQY6DqSmAfPVwWiIKHXGO6zfKX1ac4UiMbH/9oiY1VhELaH1JaH6XYgqUlDIgq+duSOWyNS34d4Sd+NoxzM3Py9T9TnM7ZrDKQxnWqki2GDjpLRTgmEZotQ6TelNF/+YCdKOKq8NeUZQrN2ZyTkwG1xs20JrOtU/FJZxdbbhkyqyfchjsB+aRBKQUr088q6XfNr3t9L2DVCRMXvYSmKR/z9yJwb2jS5w=
        file_glob: true
        file:
          - "build/**/thank-you-matcher-*.tar"
          - "build/**/thank-you-matcher-*.zip"
          - "build/**/thank-you-matcher=*-sources.jar"
          - "build/**/thank-you-matcher=*-javadoc.jar"
        skip_cleanup: true
        draft: true
        on:
          tags: true