dist: trusty
sudo: false

language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "hoby-nye"
    token: ${SONAR_TOKEN}
    github_token: ${GITHUB_TOKEN}
    branches:
      - *

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod -R +x .

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

script:
  - gradlew clean check
  - sonar-scanner