language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: hobynye
    token:
      secure: "TRkWefQYbmBRBOU8RevEKQuuIqPKlQ6glEShf2hQIz1NsBzURmkulpIcJK8vxCDH2InIUI1OoJB7SSZt5nDixdp1AstXgCeIWkePqnzyGcpNmrzBTR11ILSDZ6Jj/+H+kl6ykyBp3QAJPC5ghzb7q6d9XC0OZGXb7siwbLnv8TUIOeDKxDr7Z2o4sapBN9SZL0kPJvobU8fQ+heN77EjqVtIXKQSCLdHm+PnHT9rmHB7JJDla3By39KyW+ZieN7MXfcP9/33RzKHTlZop6wTA8D6nl3rDLa1wnQd2WUfGeV6p2AdegFl4XP0k+/XgrxOodcTz3zpY2R7VYLPkpd61tPTKNQCNnB/PX8/f9SC8E78gH1DCDYoHbD3pFq6hb9j0PRTCP0IfIjk3KSv2lPzZ6AHY7kwvaLYabMZhBbmtNDl2QsRK7s8e131r7xaHxEnMDLYiBQd62hAzUj8SXIdEZF7aFAJy+vleYsxf1eaLJ70tz1Y01no6edB9+0T8GbtDXmUw/mt46+ZyREUtRNH8l/BuPKgaojqvkRUrkW1BDR8avCByKHvJ+iCsXL7I8inzaJo71emKn2OVShPzfvJsPvgBkGCmAHxhEu0J9Ack7iivTxLF92nwkI4wyyVrQTciN9LtlhCgCsnvMEdDq/5+9VTvlZulTknpVakdGxyZow="
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod -R +x .

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

script:
  - ./gradlew clean build
  - ./gradlew sonarqube
